/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fajhri.apotek;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fajhri
 */
public class TransaksiDetail extends javax.swing.JFrame {

    private final Integer uID;

    /**
     * Creates new form TransaksiDetail
     * @param fullName
     * @param uID
     */
    public TransaksiDetail(String fullName, String username, Integer uID) {
        initComponents();
        db = new DB();
        userFullName = fullName;
        userUsername = username;
        userID = uID;
        this.uID = uID;
        
        this.setTitle("Tabel Riwayat Transaksi");
        this.setLocationRelativeTo(null);
        
        showTable();
        
        labelNamaLengkap.setText(userFullName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNamaLengkap = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNamaLengkap.setFont(new java.awt.Font("Fira Code", 2, 24)); // NOI18N
        labelNamaLengkap.setText("jLabel1");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNamaLengkap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNamaLengkap))
                    .addComponent(btnKembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Home home = new Home(userFullName, userUsername, userID);
        home.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * showTable
     */
    private void showTable() {
        try {
            table = new DefaultTableModel(new String[]{"Kode Obat", "ID Pelanggan", "Total Bayar", "Total Kembalian", "Total Harga", "Total Barang", "Tanggal"}, 0);
            // table.addColumn("Kode Obat");
            // table.addColumn("ID Pelanggan");
            // table.addColumn("Total Bayar");
            // table.addColumn()
            
            ResultSet result = db.getAllHistoryOfTransaction(userID);
            while (result.next()) {
                table.addRow(new Object[]{
                    result.getString("kode_obat"),
                    result.getInt("id_pelanggan"),
                    result.getString("total_bayar"),
                    result.getString("total_kembalian"),
                    result.getString("total_harga"),
                    result.getInt("total_barang"),
                    result.getString("tanggal_transaksi")
                });
            }
            
            tabelTransaksi.setModel(table);
            jScrollPane1.setViewportView(tabelTransaksi);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private final DB db;
    private DefaultTableModel table;
    private final String userFullName;
    private final String userUsername;
    private final Integer userID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNamaLengkap;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
